### ISSUE TITLE
"Error loading /config/configuration.yaml: mapping values are not allowed here"

### ISSUE THREAD

**Issue by MicheleMercuri** [andbad/HA_PowerControl#10]
Ha mi restituisce (al controllo) il seguente errore una volta installato tutto e (credo) configurato correttamente: `"Error loading /config/configuration.yaml: mapping values are not allowed here"`

da cosa può dipendere? grazie.

**Comment by andbad** [comment]
Non ti da altri dettagli? Dovrebbe dire anche qualcosa del tipo
`in "/config/automations.yaml", line 11, column 18`

By(t)e

**Comment by MicheleMercuri** [comment]
ciao ho risolto era un mio errore di configurazione, avevo commesso un errore nel correggere 
`    # Spengo il carico
    - service_template: switch.turn_off`
  che mi dava “DEPRECATED" e l'avevo impostato in
`    # Spengo il carico
    - service: switch.turn_off`
    sbagliando a digitare.
