### ISSUE TITLE
problema configurazione/funzionamento

### ISSUE THREAD

**Issue by mero1978** [andbad/HA_PowerControl#11]
salve, premetto che non sono esperto di homeassistant e sono alle prime armi. dopo aver configurato come da guida il package in questione al superamento della soglia imopostata non avviene nessuno stacco. volevo capire gentilmente se bisogna intervenire e configurare in qualche modo anche il file "update_entityes" salvato nella cartella python_script perchè è l'unica cosa che non ho fatto. se si è possibile avere un esempio in modo da poter prendere spunto? chiedo scusa ma sono veramente alle prime armi. grazie della disponibilità.

**Comment by andbad** [comment]
No, lo script python non è da modificare.
Puoi mandare la schermata di come hai configurato il package?

By(t)e

**Comment by mero1978** [comment]
![CC82610A-5444-431C-982B-4B04E32522D3](https://user-images.githubusercontent.com/41541857/156049147-5dedd35b-d03e-4828-a1c3-65c8e20321c0.png)
![6134174D-EBC7-45A6-B4BA-202FC0AE84D4](https://user-images.githubusercontent.com/41541857/156049165-8e91dc32-2427-4a48-bcc4-73de096b2ac9.png)

questo è quanto🤷🏻‍♂️

**Comment by mero1978** [comment]
![33C10EF3-5B77-4C7C-B01F-DB27F1951F83](https://user-images.githubusercontent.com/41541857/156050295-f8e67432-fee6-412a-9bf3-92151d7b6eb7.png)

sia qua su potenza in uso che sulla foto sopra dove vedi scritto contatore generale ho impostato l’entità dello shelly em che misura il carico totale sulla fase dell’impianto. Sicuramente sbaglio qualcosa ma non riesco a capire cosa

**Comment by andbad** [comment]
Per caso hai modificato il codice delle card lovelace mettendo il nome delle tue entità al posto degli input_select?

By(t)e

**Comment by andbad** [comment]
Ehm, no. :)
Devi semplicemente copiare il codice, poi vai nell’interfaccia grafica e imposti tutto da lì. 

By(t)e

**Comment by mero1978** [comment]
Ok perfetto!! Abbi pazienza x un povero ignorante in materia 😰😰ma sto cercando di imparare xchè mi piace. Bene l’importante é capire dove risiede l’errore. Appena arrivo a casa sistemo la cosa e ti faccio sapere. Intanto ti ringrazio veramente di cuore x la tua disponibilità, sei stato gentilissimo. Grazie grazie grazie

**Comment by mero1978** [comment]
![C0FA9554-7027-40BF-A154-5BB317BEC54F](https://user-images.githubusercontent.com/41541857/156215783-6a8389a6-be4d-470a-8636-cedfcdabd693.png)
Qui è giusto così o devo fare altro? Ho solo messo il sensore monitoraggio carico generale? 😤😤mi sta facendo esaurire sta cosa😅😅

**Comment by andbad** [comment]
Perché continui a commettere lo stesso errore. Non devi editare l'interfaccia. Tu copia e incolla il codice, poi vai nell'interfaccia, clicchi sui campi a discesa e selezioni quello che devi selezionare.
La stai facendo più difficile di quanto sia in realtà. :-)

By(t)e

**Comment by mero1978** [comment]
Ok capito il succo ma se vado nell’interfaccia e clicco sulla freccia x far scendere la tendina e selezionare mi compare solo la scritta seleziona e non mi fa selezionare nulla🤷🏻‍♂️🤷🏻‍♂️
![33805B8A-7DBE-41A7-AB1A-B3AA91D8E524](https://user-images.githubusercontent.com/41541857/156238169-936a4992-a5fb-4b46-b3bc-d1f20a3c8f9f.png)

**Comment by andbad** [comment]
Per prima cosa, controlla che l'opzione "Nuova modalità selezione opzioni" sia DISATTIVATA.
Se anche così nel menu a tendina non ti dovesse comparire nulla, devi controllare se hai correttamente copiato ed attivato gli script python.
Se dopo queste verifiche (ed un riavvio di Home Assistant) non dovessi risolvere, dovresti gentilmente attivare i log (https://github.com/andbad/HA_PowerControl#debug) ed inviarli qua sotto.

By(t)e

**Comment by andbad** [comment]
Riguardo alla tua prima domanda, se hai installato l'ultima versione, trovi l'opzione nella pagina di configurazione del pacchetto, assieme a tutte le altre opzioni, nello specifico qui:
![image](https://user-images.githubusercontent.com/7837288/156403971-4fef3dc4-3d42-434a-af4b-6c4b6a2ef4b6.png)

Riguardo la seconda domanda (come fare per controllare che gli script funzionino) ti riporto quanto detto prima.

> Se dopo queste verifiche (ed un riavvio di Home Assistant) non dovessi risolvere, dovresti gentilmente attivare i log (https://github.com/andbad/HA_PowerControl#debug) ed inviarli qua sotto.

By(t)e

**Comment by mero1978** [comment]
Nuova modalità selezione opzioni non ce l’ho quindi significa che non ho installato l’ultima versione, riguardo i log puo essere una cosa simile?
![0F9D9FFF-7EB5-472D-ACD4-DFF489FB30EB](https://user-images.githubusercontent.com/41541857/156408703-efe219a4-936c-4fd1-9be3-990fc55d7598.png)

**Comment by andbad** [comment]
Ok, bene. Intanto se scarichi l'ultima versione è meglio, così siamo allineati.

Poi, dall'errore dice che non riesce a trovare gli script python. Forse non li hai messi nel path giusto.
Vai qui, dall'interfaccia di Home Assistant: 
Configurazione (ingranaggio in basso a sinistra) -> Impostazioni (ultima voce in basso) -> Informazioni (in alto)

C'è una riga dove dice qualcosa del tipo:
"Percorso del file configuration.yaml: /home/andbad/.homeassistant"

Verifica che in quel percorso, ci sia la sottocartella "python_scripts" con dentro i due file "update_entities_new.py" e "update_entities.py".

By(t)e

**Comment by mero1978** [comment]
Fatto! Installato ultima versione ma dove dici tu vedo solo questo
![639A62D3-4EC5-494B-B9DD-88821FE88FF5](https://user-images.githubusercontent.com/41541857/156421577-e705b59f-8422-4c89-bd04-4f94f9f0c4c9.jpeg)

**Comment by mero1978** [comment]
Ok credo proprio che il problema sia riguardo il python_script vista la notifica…
![0D86A0E5-1F0C-438C-8251-99C4BA30310F](https://user-images.githubusercontent.com/41541857/156425660-870e0e84-71e9-4437-b8bb-36a9e56a4bc4.png)

che fare a questo punto?

**Comment by mero1978** [comment]
Comunque la cartella python_script con dentro i file ce l’ho in config dove risiede anche il configuration.yaml

**Comment by andbad** [comment]
Sembra che tu non abbia attivato correttamente l'integrazione python.
Puoi postare il tuo configuration.yaml? (ricordati di mascherare eventuali dati sensibili)

By(t)e

**Comment by mero1978** [comment]
Lo immaginavo. Con l'occasione mi dici se va bene la configurazione dei package xchè non sono nemmeno convinto di quelli🤷🏻‍♂️![image](https://user-images.githubusercontent.com/41541857/156572889-e87f4821-a374-4c11-b8ea-5cf544c6bcc6.jpeg)
![image](https://user-images.githubusercontent.com/41541857/156572932-09513b51-793c-4642-b374-637b01f9a8b8.jpeg)

**Comment by andbad** [comment]
Prova a togliere i due spazi prima di "python_script"
Da quello che posso vedere anche il component "logger" non è ben indentato.

By(t)e

**Comment by mero1978** [comment]
Avevo già provato a togliere i due spazi ad è proprio togliendoli che mi da la notifica di errata configurazione

**Comment by mero1978** [comment]
Tu come imposteresti il tutto?

**Comment by andbad** [comment]
Non potendo vedere tutto il codice non è facile. Prova ad aggiungere due spazi per allineare l'indentazione.

By(t)e

**Comment by andbad** [comment]
Infatti da quel che vedo ci sono un po' di problemi di indentatura. YAML è molto noioso quanto a spazi, IMHO dovresti cercare di ordinarli un po' (per es. "tts" è nel posto sbagliato), sennò va a finire che diventi matto e poi il problema è una stupidata.
Questa per esempio è una parte del mio file configuration.yaml

![image](https://user-images.githubusercontent.com/7837288/156806160-ec2e200c-dba0-427b-9156-a53efb0c3e81.png)


By(t)e

**Comment by mero1978** [comment]
Immagino sia solo un problema di dicitura nel file yaml ma non essendo molto pratico diventa ancora più ostico. Vabbè poi provo e ti faccio sapere

**Comment by mero1978** [comment]
Ho cercato di fare un po' di pulizia ma ora mi compare questo😡😡😡😡😡
![image](https://user-images.githubusercontent.com/41541857/156817525-159bd248-ec3a-4347-bf20-0d2a25e33baf.jpeg)

**Comment by mero1978** [comment]
Scusa eh...mi sorge un dubbio...il package pc.yaml che si doveva copiare dentro alla cartella package lavora assieme allo script_python? Xchè il mio dubbio è che possano essere anche i package non abilitati...che dici?
Magari ci sbattiamo x una cosa quando é un'altra🤷🏻‍♂️
Ragiono sempre da profano😰

**Comment by andbad** [comment]
Se i package non fossero abilitati, nella pagina di configurazione del package avresti decine di errori perché non trova le entità. Invece quelle le trova, quindi il problema è sullo script. I casi sono due:

1. Non sono abilitati gli script phyton
2. Non è configurata la cartella corretta.

By(t)e

**Comment by mero1978** [comment]
Ok e cm verifico se la cartella é configurata giusta? Le sto provando tutte e non ne vado fuori😫😫

**Comment by andbad** [comment]
Giusto per curiosità, avevi provato lo script di test della guida?
https://www.home-assistant.io/docs/configuration/packages/

By(t)e

**Comment by mero1978** [comment]
Scusa abbi pazienza non me ne volere quale script? A quel link si parla di package e non capisco a quale script ti riferisci...o forse sono così rincoglionito da non capirci una mazza...cosa probabile😬

**Comment by andbad** [comment]
No, no, sono io il rincoglionito. Il link giusto è:
https://www.home-assistant.io/integrations/python_script/

By(t)e

**Comment by mero1978** [comment]
Ah ok era il link sbagliato...mi stavo preoccupando😰😰 ho pensato: possibile che sono così rincoglionito da non vedere sto benedetto script?!! Tranquillo no problem succede. Poi quando arrivo a casa provo e ti faccio sapere. Mi sa che dovrò offrirti una pizza x la disponibilità risolta sta storia😅

**Comment by mero1978** [comment]
Allora...creato lo script hello_world.py e riavviato home assistant ma quando vado su servizi x richiamare lo script non lo vedo proprio🤷🏻‍♂️

**Comment by andbad** [comment]
Ok, dunque a questo punto non è un problema del mio package ma dell'attivazione degli script python sulla tua istanza di Home Assistant o della cartella dove hai messo gli script.
Ti consiglio di chiedere aiuto su questo canale Telegram:
https://t.me/indomus_chat

Magari trovi qualcuno che ti sa dare qualche dritta in più.

By(t)e

**Comment by mero1978** [comment]
Ok. Ti ringrazio veramente di cuore x la disponibilità datami fino ad ora. Grazie davvero
