### ISSUE TITLE
Errore aggiorna lista controllo carichi

### ISSUE THREAD

**Issue by leovj** [andbad/HA_PowerControl#12]
Ciao Mauro e complimenti per il tuo lavoro! Ho aggiornato HA e il tuo package all’ ultima versione presa da GitHub. Ho un problema il registro mi da questi due errori, ma smanettando un pò non riesco a capire quale può essere il problema. Puoi aiutarmi?
<img width="887" alt="Schermata 2022-03-04 alle 16 31 57" src="https://user-images.githubusercontent.com/6884242/156793605-cd3c0995-655c-4245-b494-f7dc372849a0.png">
<img width="918" alt="Schermata 2022-03-04 alle 16 32 04" src="https://user-images.githubusercontent.com/6884242/156793614-054db790-7763-4d82-8933-79b765088ae9.png">

**Comment by andbad** [comment]
Ciao,
ti ringrazio per i complimenti, ma non mi chiamo Mauro e nel mio package non c'è un'automazione con quel nome.

Immagino tu stia cercando di usare questo package:
https://hassiohelp.eu/2020/10/14/nuovo-controllo-carichi/

Ti conviene chiedere lì, dunque non ho modo di aiutarti. ☺️ 

By(t)e

**Comment by leovj** [comment]
Hai ragione scusami!!!!!  Si stavo usando proprio quel package li e cercando tra le repository pensavo fosse questa :( Adesso ho visto che questo è un altro package.. Sorry!
Visto che sono capitato qua per caso voglio provare il tuo package mi sembra molto valido! Grazie e scusa di nuovo :)
