### ISSUE TITLE
Interfaccia Lovelace

### ISSUE THREAD

**Issue by leovj** [andbad/HA_PowerControl#14]
Intanto complimenti per l'ottimo lavoro!!!! Il tuo package dopo averne provati altri mi sembra il più completo e fatto bene infatti gestisce e controlla i carichi da spegnere in maniera intelligente, verificandone l'assorbimento cosa che quello che usavo non faceva creandomi problemi (spegneva elettrodomestici che non stavano assorbendo nulla) e poi gestische le riaccensioni (quello che avevo prima riaccendeva solo l'ultimo carico).
Fatta questa dovuta premessa sono passato all' installazione, ho però un dubbio quando ho aggiunto il codice all' interfaccia Lovelace se la lascio in modifica riesco a vedere il bottone speedmeter che mi porta alla pagina del package se clicco su FATTO questo scompare!
<img width="1333" alt="Schermata 2022-04-01 alle 11 09 45" src="https://user-images.githubusercontent.com/6884242/161233402-8a89aebe-a5cf-4cf0-a535-4810bf2e25cc.png">
<img width="1323" alt="Schermata 2022-04-01 alle 11 09 58" src="https://user-images.githubusercontent.com/6884242/161233420-0415983c-5b8b-43ba-aa9d-868d9b31a887.png">

**Comment by andbad** [comment]
Prova a cliccare sulla matita accanto all'icona e farmi uno screenshot del popup che appare, così cerchiamo di capire cosa c'è che non va.

By(t)e

**Comment by leovj** [comment]
****RISOLTO****
Abbi pazienza trovato l'errore.. non era acceso il mio utente su Visibilità (pensavo lo facesse in automatico!)
Dato che ci siamo avrei anche un altra domanda: io non ho tutti gli elettrodomestici sotto misurazione ed ho un PZEM a monte subito dopo il contatore. Questo sensore creato, che mi da l'assorbimento totale della casa dove lo devo inserire?

**Comment by andbad** [comment]
Bene.

By(t)e
