### ISSUE TITLE
Traduzione in inglese di HA_PowerControl

### ISSUE THREAD

**Issue by leofabri** [andbad/HA_PowerControl#15]
Ciao @andbad ti scrivo perché i nostri amici anglofoni vorrebbero utilizzare la tua soluzione, ma [hanno difficoltà](https://community.home-assistant.io/t/notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes/254841/129?u=leofabri) a capirla per via della barriera linguistica.

**Recentemente, ho introdotto la sueguente blueprint:**
[🔌 Detect and monitor the status of an appliance based on its power consumption - V2.0.0 ✨](https://community.home-assistant.io/t/detect-and-monitor-the-status-of-an-appliance-based-on-its-power-consumption-v2-0-0-updated/421670) che utilizza il input_number.potenza_x_sospesa per rendere l'elettrodomestico consapevole di aver causato un sovraccarico.

Come dicevo, vorrei realizzare una versione inglese di HA_PowerControl perché in tanti sono interessati. Stavo lavorando per renderla disponibile, tuttavia, siccome sei tu l'autore, non voglio fare cose senza il tuo permesso e vorrei sapere come procedere quando la traduzione sarà completata.
Grazie in anticipo!

**Comment by andbad** [comment]
Ciao,
è un piacere se il mio lavoro è ritenuto utile.
Non ho ben capito se vuoi realizzare una "semplice" traduzione o se vuoi integrare la logica in una blueprint.
Nel primo caso, ammetto di non essere un grande esperto di GitHub (in realtà non sono un grande esperto di niente :-) ), ma potresti fare un fork o addirittura una pull da integrare nel progetto, magari con un'opzione per selezionare la lingua. Possiamo lavorarci.
Nel secondo caso, più che darti la mia approvazione (magari subordinata ad una citazione al mio package) non saprei come aiutarti, perché non conosco le blueprint (cioè, so cosa sono e come funzionano ma non come si scrivono).

Fammi sapere.

By(t)e

**Comment by leofabri** [comment]
Trovo che il tuo package sia un'ottima soluzione al problema dei sovraccarichi! Lo uso da tempo e sono molto soddisfatto. 
La mia blueprint si collega alle entità di tipo `input_number.potenza_x_sospesa` per rendere l'elettrodomestico consapevole di aver causato un sovraccarico. La tua soluzione è essenziale per questo e sono stupito che in giro non ci siano idee simili alla tua.

Quello che vorrei fare per ora non è una blueprint, vorrei invece tradurre l'intera repo HA_PowerControl e realizzare qualcosa totalmente tradotto in Inglese; variabili ed entità comprese.

L'idea è quella di caricare il package tradotto su una nuova repository. Questo perché tutti questi cambiamenti costringerebbero gli utenti che lo hanno già installato a reimpostare tutto, e magari potrebbero avere difficoltà con l'Inglese. 

Tradurlo in più lingue e aggiungere la possibilità di selezionare quella preferita sarebbe fantastico, ma temo che HA non ci sia d'aiuto (non sembra molto flessibile).

Ovviamente ci sarebbero credits verso il tuo user 😃!

**Comment by andbad** [comment]
Va benissimo, procedi pure. :+1: 
Se c'è qualcosa di non chiaro chiedi pure.

By(t)e

**Comment by leofabri** [comment]
Grazie mille @andbad! Appena possibile mi metterò al lavoro per realizzare la versione in inglese. 
Direi che posso chiudere la discussione.

**Comment by whulshof** [comment]
Hi, did anything happen on this translation? I already did the README and I wanted to discuss if we should translate the entity names and such as well?

**Comment by leofabri** [comment]
My plan was to translate everything into English, including entity names. I didn't have enough time to do this unfortunately. 

I've noticed a major problem with this package: After restarting Home Assistant, if an appliance was suspended, the socket is never turned on automatically, so the appliance never resumes its job.

**Comment by whulshof** [comment]
I'm translating the package right now, but I wanted to know if my effort is useful. I guess we'll have to find some solution for the HA restarting problem....

**Comment by leofabri** [comment]
Well, I guess we could find a solution (like I did on [ASM](https://github.com/leofabri/hassio_appliance-status-monitor) with the reverse timer thing), but I'm not sure if that's possible. I honestly wanted to make this package (which is basically a set of blueprints) more compact and less messy, in the sense that I wanted to minimize the number of helper entities involved as well as the number of automations and services.
If you make a translation of this, it's definitely better than nothing, and it'd be really helpful to many.

**Comment by whulshof** [comment]
Give me a few days. I'll come back to you when I have it done. What do you think, a special repo or a pull request?

**Comment by leofabri** [comment]
That's great! I'd make a new repo for this project

**Comment by whulshof** [comment]
OK, I forked the andbad repo. I'll give it a bit different name for the English version, if @andbad doesn't mind?

**Comment by whulshof** [comment]
I need this "overload protection" function for my hourly tariff optimisation automation. In winter there are not so many cheap hours and to get all the needed energy for heat pumps and EV's will be quite a stretch. I have 3 x 40 Amps, so quite some oomph, but with a possible 34 - 45 kW (48 - 63 A) load it will certainly not work without safety precaution.

**Comment by andbad** [comment]
> OK, I forked the andbad repo. I'll give it a bit different name for the English version, if @andbad doesn't mind?

You can use whatever name you like. :-)

By(t)e

**Comment by andbad** [comment]
> My plan was to translate everything into English, including entity names. I didn't have enough time to do this unfortunately.
> 
> I've noticed a major problem with this package: After restarting Home Assistant, if an appliance was suspended, the socket is never turned on automatically, so the appliance never resumes its job.

Can you open a new issue for that?
TY

By(t)e

**Comment by whulshof** [comment]
@andbad, @leofabri, I translated the everything and committed to whulshof/HA_PowerControl_en. I still have to test though. For sure there are some typo's, omissions etc.
