### ISSUE TITLE
IMPOSSIBILE MODIFICARE CONFIGURAZIONE SALVATA

### ISSUE THREAD

**Issue by chicco83** [andbad/HA_PowerControl#16]
ho effettuato una prima configurazione ed è stata salvata correttamente.
adesso pero se torno sulla interfaccia per modificare una qualsiasi tendina, ad esempio cambiare un sensore di carico tutte le tendine sono vuote e mostrano solo la voce "seleziona"
![image](https://user-images.githubusercontent.com/10348882/171513305-836e8017-6d56-454e-9800-919cc544399a.png)

**Comment by andbad** [comment]
Prova a riavviare Home Assistant, quel problema si verifica quando non viene avviato correttamente lo script python.
Abilita anche i log e inoltrameli, così vediamo qual è il problema.

By(t)e
