### ISSUE TITLE
Configurazione - Salva: Already running

### ISSUE THREAD

**Issue by leovj** [andbad/HA_PowerControl#17]
Buongiorno mi sono accordo sul log di un WARNING:

2022-06-22 13:53:36 WARNING (MainThread) [homeassistant.components.automation.powercontrol_configurazione_salva] PowerControl - Configurazione - Salva: Already running

Ma non riesco a capire da dove venga fuori..

**Comment by andbad** [comment]
L'automazione viene eseguita quando cambi qualche valore nella configurazione. Il warning avvisa che non può avviare l'automazione perché è già in esecuzione (probabilmente hai modificato due valori così velocemente da non darglil il tempo di terminare.
Se imposti il logger su "debug" possiamo controllare l'esecuzione dei vari script e automazioni e capire se c'è qualcosa che si blocca.

By(t)e

**Comment by leovj** [comment]
Ok ho aggiunto:
logger:
  default: debug
al configuration.yaml e stanno uscendo milioni di pagine di debug a me incomprensibili..:)

**Comment by andbad** [comment]
Fin qui è tutto ok, devi individuare altri log intorno al warning che hai indicato nel primo post.

By(t)e
