### ISSUE TITLE
Non funziona con HA 2022.9.x

### ISSUE THREAD

**Issue by viperxeno** [andbad/HA_PowerControl#18]
@andbad 
Ho inserito il file pc.yaml dentro la cartella packages e i 2 phyton script dentro la cartella phyton_scrpits. Purtroppo non funziona nulla.

Ho la versione 2022.9.2 di home assistant

Allego le foto.

**Comment by viperxeno** [comment]
![Screenshot_20220912-232529_Home Assistant](https://user-images.githubusercontent.com/105608752/189810489-31e5bebc-2c35-4ace-852a-d757e7c00f53.jpg)
![Screenshot_20220913-063748_Home Assistant](https://user-images.githubusercontent.com/105608752/189810492-5dd1d056-1e19-451c-9998-380eb03192be.jpg)
![Screenshot_20220913-063754_Home Assistant](https://user-images.githubusercontent.com/105608752/189810494-e4a55450-b645-4949-801d-a7f4b4f1e8f4.jpg)
![Screenshot_20220913-063805_Home Assistant](https://user-images.githubusercontent.com/105608752/189810497-9364c215-5758-40c5-8316-3ef2187fb65f.jpg)
![Screenshot_20220913-063813_Home Assistant](https://user-images.githubusercontent.com/105608752/189810499-7c2d7bb3-e1d3-4303-947e-934b22994384.jpg)
![Screenshot_20220913_063844](https://user-images.githubusercontent.com/105608752/189810501-ceaddefe-4a5f-4bc2-aa49-7ce69643b32f.jpg)
![Screenshot_20220913_063923](https://user-images.githubusercontent.com/105608752/189810504-b0715aa1-cd29-4122-97dd-bb23ea5be120.jpg)
![Screenshot_20220913_063940](https://user-images.githubusercontent.com/105608752/189810506-cb87ce83-6d4c-447b-8b79-33a41f901056.jpg)

**Comment by andbad** [comment]
Hai [abilitato i packages](https://www.home-assistant.io/docs/configuration/packages/)?
E gli [script python](https://www.home-assistant.io/integrations/python_script/)?

By(t)e

**Comment by viperxeno** [comment]
Nella directory "python_scripts" devo copiare entrambi i file "update_entities.py" e "update_entities_new.py" ? Perché dentro il file .zip in allegato trovo soltanto il file "update_entities.py"

**Comment by andbad** [comment]
Entrambi sarebbe meglio.

By(t)e

**Comment by viperxeno** [comment]
@andbad ho risolto e funziona. Tuttavia i file allegati sotto la versione 3.3 sono della versione 3.2, sia i file singoli che il file .zip. Sarebbe da sistemare

**Comment by andbad** [comment]
> @andbad ho risolto e funziona. Tuttavia i file allegati sotto la versione 3.3 sono della versione 3.2, sia i file singoli che il file .zip. Sarebbe da sistemare

Dovrei essere riuscito a sistemare.
https://github.com/andbad/HA_PowerControl/releases/tag/v3.3b

By(t)e
