### ISSUE TITLE
Aggiornamento 3.3

### ISSUE THREAD

**Issue by leovj** [andbad/HA_PowerControl#19]
Ho aggiornato alla versione 3.3 ma la "Nuova modalità selezione opzioni" Non sembra funzionare..

<img width="619" alt="Schermata 2022-09-22 alle 10 30 33" src="https://user-images.githubusercontent.com/6884242/191700659-e45e7098-4eac-438b-ba47-8c54f4aef9c7.png">

**Comment by andbad** [comment]
Ho rilasciato una nuova sottoversione, puoi vedere se con questa il problema si risolve?
https://github.com/andbad/HA_PowerControl/releases/tag/v3.3b

By(t)e

**Comment by leovj** [comment]
Grazie dopo la provo!

**Comment by leovj** [comment]
Funziona! Grazie!
