### ISSUE TITLE
Come impostare i carichi

### ISSUE THREAD

**Issue by terzo33** [andbad/HA_PowerControl#20]
Ciao @andbad , sto facendo delle prove ma non funziona come dovrebbe (ho la versione 3.3b)
Ho impostato per prova il limite di carico di stacco immediato a 1500 w ed accendere piu elettrodomestici contemporaneamente arrivando a oltre 4500w(ho un contatore da 4.5kw) ... se supera i 1500w stacca soltanto l'ultimo carico e soltanto se in uso(altrimenti non stacca nulla)con priorità minore ma comunque l'assorbimento rimane sopra i 1500w(circa 3500w) e non stacca mai i carichi successivi. Come mai?

![Screenshot_20221129_091242_Home Assistant](https://user-images.githubusercontent.com/71357473/204481497-759d4787-d31f-4080-b402-2ff6a119b696.jpg)
![Screenshot_20221129_091317_Home Assistant](https://user-images.githubusercontent.com/71357473/204474978-f5ad23c1-0d7b-4967-a627-916bccdb8f1e.jpg)
![Screenshot_20221129_094420_Home Assistant](https://user-images.githubusercontent.com/71357473/204481708-df3d2d62-7282-4557-b7ff-da8ee6ed81ab.jpg)

Allego anche il video...

https://user-images.githubusercontent.com/71357473/204487666-766958cf-f8f2-4911-ac03-ac0c35706c53.mp4

Poi se la potenza supera i 1500w da me impostati ma il carico con priorità minore non è in uso... non stacca nulla. Allego video...

https://user-images.githubusercontent.com/71357473/204490710-d6b8a830-25c3-417e-9b8c-72cc5e65f7cb.mp4

**Comment by andbad** [comment]
Prova a impostare "Potenza massima Ritardato" ad un valore minore rispetto a "Potenza massima immediato", per esempio 1400W, e rifai la prova.
Stai utilizzando una configurazione che non avevo previsto (e che ha poco senso, in effetti).

Per quanto riguarda la configurazione dei carichi, così come hai fatto va benissimo. Se un carico non viene configurato viene ignorato. Volendo potresti configurare (ad esempio) l'1, il 5, il 10 ed il 20 e lasciare quelli in mezzo vuoi (se magari pensi di inserire altri carichi e non vuoi stare a spostarli tutti).

By(t)e

**Comment by terzo33** [comment]
Ti allego anche questo video...

https://user-images.githubusercontent.com/71357473/204495609-8c2afe83-381b-4da8-b8f1-da7e74e747bd.mp4

**Comment by terzo33** [comment]
> Prova a impostare "Potenza massima Ritardato" ad un valore minore rispetto a "Potenza massima immediato", per esempio 1400W, e rifai la prova. Stai utilizzando una configurazione che non avevo previsto (e che ha poco senso, in effetti).
> 
> Per quanto riguarda la configurazione dei carichi, così come hai fatto va benissimo. Se un carico non viene configurato viene ignorato. Volendo potresti configurare (ad esempio) l'1, il 5, il 10 ed il 20 e lasciare quelli in mezzo vuoi (se magari pensi di inserire altri carichi e non vuoi stare a spostarli tutti).
> 
> By(t)e

Provo con questa configurazione... forse tu lo stacco immediato lo intendi se si raggiunge un assortimento che va oltre la potenza contrattuale. Però mettiamo supero i 6000w e lui stacca soltanto l'ultimo carico che assorbe 1000w comunque rimango a 5000w quindi oltre la soglia contrattuale per cui dovrebbe staccare anche gli altri carichi successivi cosa che non fa, magari sbaglio il ragionamento.

**Comment by andbad** [comment]
Infatti dovrebbe fare così: stacca il carico a più bassa priorità ma se sei ancora sopra la soglia stacca quello dopo e così via, fino a tornare sotto soglia.
Non ho controllato il codice, ma il fatto che tu abbia configurato una soglia di distacco immediato più bassa di quello ritardato faccia un po' di casino.

Le due soglie sono pensate perché il contatore in Italia funziona con quella logica: puoi assorbire per quanto tempo vuoi fino al 10% oltre la soglia contrattuale (nel tuo caso 4500W, quindi puoi assorbire fino a 4950W per un tempo indefinitio). Puoi assorbire tra il 10 ed il 30% in più per un massimo di 180 minuti (quindi tra 4950W e 5850W), prima di staccare. Se invece vai oltre il 30%, stacca immediatamente (o meglio, sul manuale dice "entro due minuti").

Di conseguenza dovresti impostare come limite ritardato 4950W e come limite immediato 5850W (consiglio di arrotondare per difetto).
Tu invece hai impostato un limite ritardato superiore a quello immediato, quindi il pacchetto stacca il primo carico ma non prosegue perché il valore resta inferiore a quello ritardato (che hai messo a 3000).
Dovresti IMHO impostare i parametri consigliati (adeguando eventualmente le potenze secondo quanto detto sopra) per farlo funzionare correttamente, anche per quanto riguarda i tempi di disattivazione e riattivazione.

By(t)e
