### ISSUE TITLE
Change the power load instead of detaching it

### ISSUE THREAD

**Issue by whulshof** [andbad/HA_PowerControl#25]
I want to use PC for controlling the load of my EV charging and heat pump operation. Both can also be "modulated", ie I could set charging from 32 A to 16 A (22 kW vs. 11 kW), without detaching the load. The same for the heat pumps. I am still translating, so not yet installed PC. Would that be possible do you think, @andbad?

**Comment by andbad** [comment]
A possible (and simple) solution is configure a "virtual switch", named for example "reduce_power_ev_charging", and use it in PowerControl configuration.
Then you can make an automation that check the status of this "virtual switch" and when turned off (when PowerControl try to detach the load) tell to EV charger to reduce the power from 32 to 16A (I don't know what EV charger you have, for example  it might need create a MQTT call). When PowerControl turn the switch on, the automation restore the initial EV charger configuration.

You can also configure two load on PowerControl: one as "virtual switch" as above and another one (with higher priority) that stop the chargin (detaching the load or telling to charger to stop charge). In this way the packege switch off the first virtual load, that cause the reduction of the charging power) and if that isn't enough (after the seconds configured in the package) stop the charging completely.

By(t)e
