### ISSUE TITLE
Cambiando la configurazione dei sensori in un secondo momento, il comportamento dell'automazione non è più corretto

### ISSUE THREAD

**Issue by dunker74** [andbad/HA_PowerControl#26]
Dopo aver installato il pacchetto l'ho configurato con solo 3 sensori di misura e 3 contatti, ho fatto delle prove e tutto funzionava correttamente. In un secondo momento ho cambiato la configurazione inserendo i 19 sensori e i 19 contatti del mio impianto ma purtroppo non sta funzionando. Quello che noto è che mi arrivano le notifiche del distacco dei carichi ma nella realtà ciò non avviene inoltre l'automazione prova a distaccare senza successo solo 3 carichi invece dei 19 inseriti. Le 3 notifiche di distacco che mi arrivano non seguono l'ordine che ho impostato di priorità. Sembra che l'automazione abbia fatto un "minestrone" della nuova e della vecchia configurazione. Grazie a chiunque riesca ad aiutarmi a risolvere il problema.

**Comment by andbad** [comment]
Ciao,
nella pagina di configurazione del package c'è una scheda tipo questa:
![Schermata 2023-02-23 10:05:35](https://user-images.githubusercontent.com/7837288/220863663-c17f142a-f81b-4f11-83b9-23fcb726235c.png)

Prova a verificare se i sensori che hai impostato nelle caselle a discesa corrispondono alla configurazione mostrata qui.

By(t)e

**Comment by andbad** [comment]
Aggiungo anche che, come sempre, sarebbe utile avere i log, così da poterli analizzare e capire esattamente cosa succede quando il package entra in azione.
Trovi le info qui: https://github.com/andbad/HA_PowerControl#debug

By(t)e

**Comment by dunker74** [comment]
Problema risolto: il malfunzionamento era dovuto alla logica negata del contatto per il distacco del carico. Ora funziona tutto perfettamente. Grazie e complimenti per lo sviluppo!
