### ISSUE TITLE
Perdita configurazione Power Control

### ISSUE THREAD

**Issue by slack1987** [andbad/HA_PowerControl#27]
Salve,

Ogni tanto mi accorgo casualmente, andando a controllare il pannello di Power Control, di avere perso tutte le impostazioni.
Il sensore di potenza e tutti i sensori dei carichi con i relativi switch spariscono e devo ri-selezionarli.

Allego uno screenshot.

**Informazioni sul sistema**
 - Versione Home Assistant: 2023.3.4
 - Tipo installazione: HASSIO
 - Versione package: 3.3
 
**Log:**
2023-03-14 14:08:50.241 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Popola entità - Avvio script python
2023-03-14 14:08:50.241 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Carica - Avvio automazione, attendo fine automazione popola_entita_per_configurazione_pc
2023-03-14 14:08:50.805 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Salva - Avvio automazione, attendo fine automazione powercontrol_configurazione_carica
2023-03-14 14:08:54.065 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Popola entità - Script python terminato
2023-03-14 14:08:54.078 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Carica - Carico input_select dai relativi input_text
2023-03-14 14:08:54.217 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Carica - Fine caricamento
2023-03-14 14:08:54.231 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Salva - Salvo input_select in input_text
2023-03-14 14:08:54.321 DEBUG (MainThread) [homeassistant.components.pc] Automazione Configurazione - Salva - Fine salvataggio

**Informazioni aggiuntive**
![Immagine 2023-03-14 152255](https://user-images.githubusercontent.com/64207585/225031440-f535cd38-7e88-4db3-913e-296bb557f1a8.png)

Altre informazioni che potrebbero sembrarti utili.

**Comment by deralex92** [comment]
Confermo certe volte trovo anch'io che perde le impostazioni!

**Comment by alpitur** [comment]
Stesso problema, perdita di configurazione e perciò inutilizzabile

**Comment by slack1987** [comment]
Confermo che da quando non ho più usato il riavvio rapido non ho più perso le impostazioni.

**Comment by lucaxxaa** [comment]
Io ho notato come hanno detto in post precedenti che si che se si fa riavvio rapido del sistema perde la configurazione, mentre Con il riavvio completo di home assistant la tiene la configurazione

**Comment by deralex92** [comment]
> Stesso problema, perdita di configurazione e perciò inutilizzabile

in realtà basta non utilizzare il riavvio rapido e funziona molto bene questo script!

**Comment by alpitur** [comment]
> > Stesso problema, perdita di configurazione e perciò inutilizzabile
> 
> in realtà basta non utilizzare il riavvio rapido e funziona molto bene questo script!

**Comment by alpitur** [comment]
Beh, nn mi sembra una gran cosa

**Comment by alpitur** [comment]
> > Stesso problema, perdita di configurazione e perciò inutilizzabile
> 
> in realtà basta non utilizzare il riavvio rapido e funziona molto bene questo script!

Difatti nn ho detto che lo script nn funziona bene, anzi. Però ripeto in queste condizioni nn è utilizzabile

**Comment by deralex92** [comment]
> > > Stesso problema, perdita di configurazione e perciò inutilizzabile
> > 
> > 
> > in realtà basta non utilizzare il riavvio rapido e funziona molto bene questo script!
> 
> Difatti nn ho detto che lo script nn funziona bene, anzi. Però ripeto in queste condizioni nn è utilizzabile

> > > Stesso problema, perdita di configurazione e perciò inutilizzabile
> > 
> > 
> > in realtà basta non utilizzare il riavvio rapido e funziona molto bene questo script!
> 
> Difatti nn ho detto che lo script nn funziona bene, anzi. Però ripeto in queste condizioni nn è utilizzabile

Si e no alla fine.. ora si sa, si evita il riavvio rapido e poi se lo sviluppatore o qualcuno trova una soluzione la pubblica.. io personalmente non ho capito dove sta all'interno del codice il problema... Qualcuno più ferrato di me lo sistemerà, spero:)

**Comment by andbad** [comment]
Il problema penso derivi dalle tempistiche di ricaricamento delle configurazioni (il riavvio rapido).
Durante l'avvio normale, le automazioni configurate per attivarsi anche all'avvio vengono richiamate come ultima cosa, dopo il caricamento di tutto il resto.
Durante l'avvio rapido, invece, le automazioni vengono richiamate prima (o durante) che vengano caricate le altre componenti, tra le quali le entità input_text che vengono utilizzati per salvare le configurazioni di PowerControl.
Di conseguenza può capitare (perché mi è parso che l'ordine con il quale vengono caricati i componenti è casuale) che si perdano le impostazioni. 
Sul come risolvere sto ancora lavorando.

By(t)e

**Comment by alpitur** [comment]
Molto gentile. Aspettiamo che si risolva il problema, perché il package è veramente di ottima fattura e molto utile. Ciao Il giorno 28 apr 2023, alle ore 12:43, andbad ***@***.***> ha scritto:﻿
Il problema penso derivi dalle tempistiche di ricaricamento delle configurazioni (il riavvio rapido).
Durante l'avvio normale, le automazioni configurate per attivarsi anche all'avvio vengono richiamate come ultima cosa, dopo il caricamento di tutto il resto.
Durante l'avvio rapido, invece, le automazioni vengono richiamate prima (o durante) che vengano caricate le altre componenti, tra le quali le entità input_text che vengono utilizzati per salvare le configurazioni di PowerControl.
Di conseguenza può capitare (perché mi è parso che l'ordine con il quale vengono caricati i componenti è casuale) che si perdano le impostazioni.
Sul come risolvere sto ancora lavorando.
By(t)e

**Comment by goldrake1981** [comment]
Complimenti , pacchetto veramente utile e intelligente.  Provavo a dare qualcosa di simile con le automazioni ma questo risolve ogni mio problema.  Come tutti anche io ho riscontrato la perdita dei dati dopo un riavvio rapido , per adesso risolvo semplicemente riscrivendo in Lovelace lo yaml precedentemente salvato sul PC.  Non vedo l'ora che si trovi una soluzione.  
Grazie

**Comment by goldrake1981** [comment]
Per adesso sembra funzionare tutto bene.  Questo pacchetto e fatto per lavorare su un contatore del GSe mentre io lo sto usando per un impianto fotovoltaico off grid.  In pratica ho un inverter da 5kw che per sua capacità non e un grado di sopportare i 5 kW per più di 10 secondi. Una cosa che forse e inutilizzabile e il tempo di attesa prima dello stacco dei carichi ritardato ( 10 minuti sono troppi).
Poi in secondi distacco immediato se imposto 0 stacca tutta la lista contemporaneamente oppure parte dall'ultimo e li stacca 1 alla volta ?( solo quelli che hanno un carico effettivo?)
Se vuoi espandere questo pacchetto alle problematiche di un inverter solare saro felice da farti da tester.
Per il momento grazie

**Comment by andbad** [comment]
> Per adesso sembra funzionare tutto bene. Questo pacchetto e fatto per lavorare su un contatore del GSe mentre io lo sto usando per un impianto fotovoltaico off grid. In pratica ho un inverter da 5kw che per sua capacità non e un grado di sopportare i 5 kW per più di 10 secondi. Una cosa che forse è inutilizzabile e il tempo di attesa prima dello stacco dei carichi ritardato (10 minuti sono troppi).
Anche io ho da poco attivato il FV (anche se on-grid), quindi devo ragionare su eventuali ulteriori ottimizzazioni in tal senso.
Se vuoi puoi modificare l'input_number relativi alla configurazione (tempo_stop_ritardato, riga 320) cambiando il valore "step" da 10 a 1 e "max" da 180 a 10: in questo modo puoi scegliere un tempo in minuti tra 0 e 10.

> Poi in secondi distacco immediato se imposto 0 stacca tutta la lista contemporaneamente oppure parte dall'ultimo e li stacca 1 alla volta ?( solo quelli che hanno un carico effettivo?) Se vuoi espandere questo pacchetto
> alle problematiche di un inverter solare saro felice da farti da tester.
> Per il momento grazie

Se imposti a zero i secondi tra un distacco e l'altro, il pacchetto staccherà tutti i carichi contemporaneamente, ma solo se stanno assorbendo. 

By(t)e

**Comment by goldrake1981** [comment]
Grazie.
Solo un altra cosa , il distacco immediato stacca tutti i dispositivi contemporaneamente o anche li usa la sequenza 1-20 e la logica che se un dispositivo non assorbe non lo stacca?

**Comment by andbad** [comment]
> Grazie. Solo un altra cosa , il distacco immediato stacca tutti i dispositivi contemporaneamente o anche li usa la sequenza 1-20 e la logica che se un dispositivo non assorbe non lo stacca?

Usa la solita logica: distacca i dispositivi che stanno assorbendo partendo dal numero 20 al numero 1 attendendo il tempo "secondi tra gli stop" tra uno ed il successivo.

`By(t)e`
