### ISSUE TITLE
Ricarica macchina elettrica

### ISSUE THREAD

**Issue by pacioc193** [andbad/HA_PowerControl#28]
**Descrivi il problema che vorresti risolvere con una nuova funzionalità**
Sto per acquistare una Tesla e vorrei trovare un modo per mettere in pausa la ricarica in caso il consumo di casa superi un determinato livello.

Hai una idea su come far funzionare il tutto?

**Comment by andbad** [comment]
Il mio consiglio è di crearti uno "switch virtuale", che quando viene acceso, chiama il servizio dell'integrazione Tesla che fa partire la carica, e quando viene spento chiama il servizio che interrompe la carica. Se l'integrazione Tesla te lo fornisce, crei un sensore che indichi la potenza assorbita, se invece non ti da questo valore, devi creare un sensore che restituisca una potenza fissa (che imposti tu manualmente)
Poi configuri questo switch come interruttore nel package ed il sensore di potenza come indicazione di assorbimento nel package (oltre agli altri parametri, ovviamente).

By(t)e

**Comment by pacioc193** [comment]
Per la corrente di ricarica non è un problema. Ho una pinza amperometrica di uno shelly 3M adibita solo a quello. Non ho mai provato ad usare uno switch. Ci proverò!Grazie milleIl giorno 20 mar 2023, alle ore 18:55, andbad ***@***.***> ha scritto:﻿
Il mio consiglio è di crearti uno "switch virtuale", che quando viene acceso, chiama il servizio dell'integrazione Tesla che fa partire la carica, e quando viene spento chiama il servizio che interrompe la carica. Se l'integrazione Tesla te lo fornisce, crei un sensore che indichi la potenza assorbita, se invece non ti da questo valore, devi creare un sensore che restituisca una potenza fissa (che imposti tu manualmente)
Poi configuri questo switch come interruttore nel package ed il sensore di potenza come indicazione di assorbimento nel package (oltre agli altri parametri, ovviamente).
By(t)e
