### ISSUE TITLE
Resettare i device in attesa se viene disabilitato il power control

### ISSUE THREAD

**Issue by Gobolin80** [andbad/HA_PowerControl#29]
Ciao,
innanzitutto complimenti per il progetto.
E' veramente ben fatto e molto ingegnoso.

Ti faccio una domanda e nello stesso tempo una proposta di evoluzione.

Sarebbe utile che, nel momento in cui il power control viene disabilitato manualmente dallo switch dell'interfaccia, il sistema resettasse le entità e la potenza "in attesa", per evitare che al successivo avvio manuale si ritrovasse in una situazione instabile.

Ti chiedo: per farlo è sufficiente settare a 0 i vari input_number.potenza_*_sospesa?

La ragione per cui propongo questa modifica è che il tuo progetto sia adatta perfettamente alla gestione dei dispostivi con l'extraproduzione del fotovoltaico.
Settando il limite massimo a 0 è possibile gestire ottimamente gli split dei condizionatori con la sola energia prodotta in eccesso.
E' ovvio che questo funzionamento deve avvenire solo nel periodo di produzione e quindi, la sera, il power control va spento.
Da qui la richiesta di poter resettare i device in attesa.

Grazie ancora per il tuo lavoro

**Comment by andbad** [comment]
Ti ringrazio per i complimenti.
Venendo alla tua richiesta, c'è già un'automazione che monitora lo stato degli interruttori e, se sono accesi, resetta gli input_number della potenza sospesa, questo per far si che se si riaccende manualmente un carico, il package non pensa che sia ancora sospeso.
Vorrei però fare qualche test per capire come si comporta alla disattivazione/riattivazione del package.

`By(t)e`
