### ISSUE TITLE
Dominio Light sugli interruttori carichi

### ISSUE THREAD

**Issue by danygi79** [andbad/HA_PowerControl#30]
Buongiorno,

bellissimo e molto funzionale il tuo package, lo uso con successo già da un paio di anni, ora però ho un'esigenza un pò diversa.
Utilizzo dei relè statici autocostruiti comandati da un esp32 tramite ESPHome per il controllo di carichi resistivi vari (soprattutto bollitori per il riscaldamente di acquia calda).
Per questo mi è molto piu comodo usare gli interruttori di tipo Light, perchè permettono di regolare anche la luminosità, parametro che poi io utilizzo per regolarne la potenza.
Il tuo progetto non prevede però l'tilizzo di tali entità per il distacco dei carichi, è possibile aggiungerli?

Grazie

**Comment by andbad** [comment]
Prova questa versione, dovrebbe andare:
https://github.com/andbad/HA_PowerControl/tree/30-dominio-light-sugli-interruttori-carichi

By(t)e
