### ISSUE TITLE
Sensore potenza carichi non selezionabile

### ISSUE THREAD

**Issue by giros79** [andbad/HA_PowerControl#31]
Ho seguito la guida passo passo , ma non riesco a selezionare il sensore potenza carico.
Dal menu a tendina c'è solo la voce SELEZIONA

**Comment by andbad** [comment]
https://github.com/andbad/HA_PowerControl#debug

By(t)e

**Comment by parisiantony** [comment]
Hi, I updated HA yesterday and after that I can't found the identities anymore.
I only see these in the picture:

![image](https://github.com/andbad/HA_PowerControl/assets/64355142/db835bd0-9b99-4f7c-a560-e2723f37ed4d)
![image](https://github.com/andbad/HA_PowerControl/assets/64355142/4917bc36-93b8-4c61-8926-bc6623edfef6)


These are the versions:
Home Assistant 2023.8.4
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230802.1 - latest

Debug enabled but no errors found:
![image](https://github.com/andbad/HA_PowerControl/assets/64355142/7f88462b-368f-4d98-8a88-e4d8778f7392)

Can you help me please?

**Comment by andbad** [comment]
> Ciao, ho aggiornato HA ieri e non riesco più a trovare le identità. Vedo solo questi in figura:
> 
> ![image](https://user-images.githubusercontent.com/64355142/266076726-db835bd0-9b99-4f7c-a560-e2723f37ed4d.png) ![image](https://user-images.githubusercontent.com/64355142/266078042-4917bc36-93b8-4c61-8926-bc6623edfef6.png)
> 
> Queste le versioni: Home Assistant 2023.8.4 Supervisor 2023.08.3 Operating System 10.5 Frontend 20230802.1 - latest
> 
> Debug attivato ma nessun errore: ![image](https://user-images.githubusercontent.com/64355142/266080466-7f88462b-368f-4d98-8a88-e4d8778f7392.png)
> 
> Mi puoi aiutare per favore? Grazie!

L'opzione "Nuova modalità selezione" è abilitata?
In caso fosse abilitata, prova a disabilitarla e riavvia Home Assistant.

By(t)e

**Comment by parisiantony** [comment]
> > Ciao, ho aggiornato HA ieri e non riesco più a trovare le identità. Vedo solo questi in figura:
> > ![image](https://user-images.githubusercontent.com/64355142/266076726-db835bd0-9b99-4f7c-a560-e2723f37ed4d.png) ![image](https://user-images.githubusercontent.com/64355142/266078042-4917bc36-93b8-4c61-8926-bc6623edfef6.png)
> > Queste le versioni: Home Assistant 2023.8.4 Supervisor 2023.08.3 Operating System 10.5 Frontend 20230802.1 - latest
> > Debug attivato ma nessun errore: ![image](https://user-images.githubusercontent.com/64355142/266080466-7f88462b-368f-4d98-8a88-e4d8778f7392.png)
> > Mi puoi aiutare per favore? Grazie!
> 
> L'opzione "Nuova modalità selezione" è abilitata? In caso fosse abilitata, prova a disabilitarla e riavvia Home Assistant.
> 
> By(t)e

Ha funzionato.
Grazie!
