### ISSUE TITLE
Variazione di potenza

### ISSUE THREAD

**Issue by Tiz-B** [andbad/HA_PowerControl#32]
**Informazioni aggiuntive**
Prima di tutto grazie per questo magnifico plugin.
Mi domandavo se fosse possibile integrare la funzione di variazione di potenza oltre allo stacco completo.
Per esempio sarebbe davvero interessante poter diminuire la potenza di carica dell'auto elettrica - nel mio caso ho uno Shelly EM che monitora la linea dedicata alla ricarica e posso variare l'amperaggio di carica da remoto del "carichino" (anche tramite HA), ma non ho la minima idea di come fare una cosa del genere partendo dal tuo lavoro.
Grazie.

**Comment by andbad** [comment]
Io non uso il mio package per ma ho scritto un'automazione apposita.
Anche perché concettualmente deve fare l'opposto: questo package stacca quando c'è troppo assorbimento, la macchina invece abbassa il suo assorbimento per non sforare (nel mio caso per seguire la produzione del fotovoltaico).

In generale il funzionamento è piuttosto semplice: parte da 12A poi fa un ciclo che se la produzione è maggiore del consumo aumenta di mezzo A la potenza di ricarica. Se invece sto assorbendo dalla rete (quindi il consumo è maggiore della produzione) diminuisce di mezzo A.
 
Questo è molto semplificato, perché in realtà tiene conto anche della batteria di accumulo (posso decidere a cosa dare la priorità) e altri controlli.

By(t)e

**Comment by Tiz-B** [comment]
Capisco grazie.
Ma si riesce a fare con un "semplice" automazione?
Non sono molto pratico di codice; si riesce con l'interfaccia grafica oppure bisogna smanettare sul file di configurazione?
Grazie

**Comment by andbad** [comment]
Non è una cosa facile fare un'automazione universale che vada bene per tutti.
E comunque non è lo scopo di questo package. :)

By(t)e
