### ISSUE TITLE
Utilizzo entità light nei menu a tendina

### ISSUE THREAD

**Issue by dgarimoldi** [andbad/HA_PowerControl#34]
Buongiorno e complimenti per il fantastico progetto.
Ho il problema di avere una entità light.xxxxx che è lo switch da accendere e spegnere per uno dei carichi monitorati

Possibile soluzione:
Far comparire anche le entità light.xxx nei menù a tendina

Grazie mille

**Comment by andbad** [comment]
Certo, puoi installare questa versione che abilita le entità light:

https://github.com/andbad/HA_PowerControl/tree/30-dominio-light-sugli-interruttori-carichi

Fammi sapere.

By(t)e

**Comment by dgarimoldi** [comment]
Grazie mille!
Funziona perfettamente ora!

Ancora complimenti per l'ottima integrazione!!!!

Il giorno mar 7 nov 2023 alle ore 11:24 andbad ***@***.***>
ha scritto:
