### ISSUE TITLE
I don't receive the notifications after having updated to latest version

### ISSUE THREAD

**Issue by slack1987** [andbad/HA_PowerControl#36]
**Informazioni sul sistema**
 _-HassOS 2023.12.1_
 _- Versione package 3.41_

After having updated the package to the latest version (3.41) I don't receive the notification anymore.

If I try to call the service and send a notification to the group "notify.tutti" I receive the notification with no problem.

I can't see any particular problem in the logs.

Any idea? Thank you.

**Comment by andbad** [comment]
I make some test and the notification works correctly.
In the latest versions I have not made any changes to that functionality.
Try a previous version to check if the problem is in the package.

By(t)e

**Comment by slack1987** [comment]
@andbad Problem solved, the notification group in my configuration was called **name: "notify.tutti"** instead of **name: "tutti"**.

Case closed! Thank you!
