### ISSUE TITLE
Più istanze contemporanemante

### ISSUE THREAD

**Issue by goldrake1981** [andbad/HA_PowerControl#37]
Buongionro,
chiedo se e possibile e come fare per avere piu istanze del power control.
La mia idea sarebbe quella di creare un sensore con la somma di diversi elettrodomestici che sono al piano terra della mia casa e condividono la stessa linea in modo da creare un Power Control solo per loro.  Non mi va che in quella linea ci siano piu di 3kw utilizzati ad esempio. 
Attualmente ho una potenza del contatore da 6 kw e capita spesso che ad assorbire e solo un piano della mia abitazione sovraccaricando quella linea, 
Grazie

**Comment by andbad** [comment]
A mio avviso potresti risolvere nel modo più efficace impostando i carichi del piano terra con una priorità minore rispetto a quelli del primo piano. In questo modo se per ipotesi di sotto prelevano 5kW e tu accendi un carico che preleva 2, quello al piano di sotto viene interrotto (perché quello di sopra ha priorità più elevata).
Se invece il problema sono i cavi che portano la corrente ad un piano sono di sezione inadeguata a reggere 6kW, usare questo package non è una buona idea, per ovvi motivi di sicurezza.

Per rispondere invece alla tua domanda, dovresti duplicare il package modificando il nome di tutti gli elementi (sensori, script, automazioni, ecc...) e configurarli di conseguenza. Ma a mio avviso non è una soluzione ottimale, perché staccheresti dei carichi senza che ve ne sia la reale necessità.

By(t)e

**Comment by goldrake1981** [comment]
Grazie della risposta.  Speravo in un modo più semplice per creare un altra istanza.  Il problema che il piano terra non è gestiti da me (nel senso che non sono io ad accendere gli elettrodomestici ) anche se condividiamo lo stesso contatore

**Comment by goldrake1981** [comment]
Si capisco.   Sto valutando il da farsi anche perché il tuo package lo utilizzo per un impianto fotovoltaico più che per Enel.  Ho la fortuna di avere Enel libero , cioè senza limiti. Ora ho preso un altro inverter che vorrei dedicare a quella linea e per questo sarebbe stato comodo la doppia istanza

**Comment by andbad** [comment]
Purtroppo non c'è un modo veloce per duplicare l'istanza. 

By(t)e
