### ISSUE TITLE
Conflitto con statistiche di home assistant

### ISSUE THREAD

**Issue by Symon84** [andbad/HA_PowerControl#38]
**Informazioni sul sistema**
 _- Versione Home Assistant_ 2024.1.2
 _- Tipo installazione (core, VENV, container, ecc...)_ container: Docker
 _- Versione package_ v 3.42
 _- HAI ATTIVATO I LOG?_ si

**Descrivi il problema**
_Dopo aver aggiornato alla versione v 3.42 tutte le statistiche di home assistant hanno smesso di funzionare.
Per ripristinare il corretto funzionamento delle statistiche sono ritornato alla versione 3.41_

**Passi per riprodurre il problema**
Indicazioni su come riprodurre le condizioni che hanno portato al bug:
_Aggiornare alla versione v.3.42 dalla versione v.3.41 nel seguente modo:_
_1. Sostituire il file "packages/pc.yaml" nella directory "packages" con ultima rev._
_2. Sostituire i file "python_scripts/update_entities.py" e "python_scripts/update_entities_new.py" nella directory "python_scripts" con ultima rev._

***Screenshot***
Sezione "Strumenti per sviluppatori/STASTISTICHE"
Tutte le statistiche si trovano in questo stato dopo il riavvio:
![image](https://github.com/andbad/HA_PowerControl/assets/97830313/21f922fb-e0ef-4c23-b260-28ee49a2c866)

***LOG***
Chiedo indicazioni su cosa pubblicare per evitare di inserire troppe informazioni.

***ALTRE INFO***
_Suppongo si tratti di un problema relativo alla modifica dei sensori template, ma non ne ho la certezza.. per quale motivo sono stati variati nella rev 3.42? 
Se così fosse probabilmente dovrò adeguare tutto il resto del codice.
Grazie_

**Comment by goldrake1981** [comment]
mi e capitato la stessa cosa, ho risolto inserendo 

```
recorder:
  purge_keep_days: 2
  auto_purge: true
  auto_repack: true
  include:
    domains:
      - sensor
      - switch
      - light
```

non credevo fosse correlato all'aggiornamento

**Comment by andbad** [comment]
No, è colpa mia, dimentico sempre di commentare la sezione "recorder".
Potete aggiornare a questa versione:
https://github.com/andbad/HA_PowerControl/releases/tag/v.3.42b

By(t)e

**Comment by Symon84** [comment]
Risolto,
grazie!!! 👍 🔝
