### ISSUE TITLE
Implementazione con produzione FV

### ISSUE THREAD

**Issue by lucatraversaro** [andbad/HA_PowerControl#40]
**Descrivi il problema che vorresti risolvere con una nuova funzionalità**
Vorrei integrare un sensore di potenza esportata e uno della percentuale di batteria del sistema fotovoltaico per gestire surplus di potenza immessa in rete."

**La tua soluzione**
A me interesserebbe prevalentemente la gestione dei carichi come bilanciamento della produzione del mio impianto fotovoltaico, quindi mi basterebbe poter assegnare il singolo carico (con potenza nota eventualmente inseribile da un altro campo) a un gruppo con l'obiettivo di ottenere vari livelli di intervento, grossolanamente ogni 1000 W di surplus. 

**Alternative**
Purtroppo, prima di imbattermi nel tuo progetto, ho fatto alcuni tentativi realizzando automazioni che variavano passo passo degli input numerici in base alle soglie di intervento e, se poi corrispondevano da quelli selezionati sul carico, avrebbero dovuto attivare il carico... Qui mi sono fermato perché non so assolutamente come fare a gestire dinamicamente la variazione di Switch (che poi nel mio caso sarebbero prevalentemente entità climate) da un gruppo a un altro. 

**Informazioni aggiuntive**
Scusa se sono stato prolisso e confuso a tratti, spero comunque di trovare riscontro alla mia idea di base che forse potrebbe servire a qualcun altro. 
Sono a disposizione per qualsiasi aiuto possa dare.

**Comment by andbad** [comment]
Ciao, grazie per il tuo suggerimento.
Quello che chiedi però è fuori dal contesto di questo package.
Personalmente ho creato delle automazioni per le singole entità da controllare in base alla produzione (una per la ricarica dell'auto, uno per la PdC e un'altro per il boiler).
In ogni caso non credo che questo package sia adattabile a questo scopo.

By(t)e
