### ISSUE TITLE
Lista dispositivi in uso e in attesa 

### ISSUE THREAD

**Issue by goldrake1981** [andbad/HA_PowerControl#43]
Ciao,
Utilizzo oramai da tempo questo fantastico soluzione per la gestione dei carichi in casa.  Fra l'altro l'ho adattata ad un inverter fotovoltaico e mi aiuta a stare sotto il limite massimo dell' inverter che nel mio caso è di 6Kw . Mi chiedevo se fosse possibile aggiungere una lista di carichi attivi e di quelli messi in attesa prendendoli dalle liste impostate ovviamente .  Credo sia utile per tenere monitorato quale carichi si sono disattivati.  Nel mio caso capita che più di un carico viene messo in attesa e non so mai quale sia.  Ho risolto un po' il problema con una scheda che racchiude tutti gli switch inseriti e mi accorgo di quale ha spento vedendo lo stato dello switch.  Tuttavia ogni tanto ho degli switch spenti perché non li uso e comunque ho dei carichi in attesa che faccio fatica a capire quale siano.
Spero di essermi spiegato bene.  Grazie

**Comment by andbad** [comment]
Grazie del suggerimento, è un'idea che potrebbe essere utile.
Penso a come implementarla.

By(t)e

**Comment by goldrake1981** [comment]
Grazie a te

**Comment by andbad** [comment]
Fatto. https://github.com/andbad/HA_PowerControl/releases/tag/v3.50b

By(t)e

**Comment by Symon84** [comment]
Fantastico, ottima idea!
Ho appena aggiornato!
Grazie

**Comment by goldrake1981** [comment]
Grande. Grazie

**Comment by goldrake1981** [comment]
scusa ma non ho capito come aggiorno questa configurazione, se copio e incollo il testo in lovelace mi da degli errori e mi crea diverse tab

**Comment by goldrake1981** [comment]
come non detto, risolto, grazie ancora
