### ISSUE TITLE
Nuova versione senza notifiche non funziona

### ISSUE THREAD

**Issue by alexcoscia** [andbad/HA_PowerControl#46]
![Screenshot_2024-06-06-19-06-24-828_io homeassistant companion android](https://github.com/andbad/HA_PowerControl/assets/101573852/a6fc96ae-afd6-4123-b27e-f742dc9a5af4)
Il distacco carichi non parte anche se si supera la soglia impostata.

**Comment by andbad** [comment]
Grazie, corretto. https://github.com/andbad/HA_PowerControl/commit/912b85ba4b63315c85e29651b9451ddc58762e5f

By(t)e
