### ISSUE TITLE
Aiuto

### ISSUE THREAD

**Issue by gregpd** [andbad/HA_PowerControl#48]
**Descrivi il problema che vorresti risolvere con una nuova funzionalità**
Ciao, come si può rimuovere l'intero pacchetto per reinstallare tutto ex novo? Sarà possibile inserire una funzione che lo faccia in automatico all'interno di "Mostra Impostazioni Power control"? 
Grazie

**La tua soluzione**
##

**Alternative**
##

**Informazioni aggiuntive**
Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

**Comment by gregpd** [comment]
ciao,
o ancora difficoltà con la cancellazione: mi rimangono tutti i sensori anche dopo aver cancellato i tre file:
./python_scripts/update_entities.py
./python_scripts/update_entities_new.py
./packages/pc.yaml
posso avere un aiutino senza dover reinstallare da zero HA?
grazie

**Comment by andbad** [comment]
Hai riavviato? Se si, probabilmente li vedi ma non sono disponibili.

- Impostazioni->Dispositivi e servizi->Entità
- Filtri->Stato->Non disponibile
- Click sul quadratino per selezionare tutte le entità
- Click sui 3 puntini in alto a destra->Elimina selezionati

By(t)e

**Comment by gregpd** [comment]
fatto, reinstallo da zero.
 grazie.
