### ISSUE TITLE
Non funzionano più i menu a tendina dopo aggiornamento HA 2024-12

### ISSUE THREAD

**Issue by Max1963** [andbad/HA_PowerControl#54]
**Informazioni sul sistema**
 _- Versione Home Assistant_ 2024.12
 _- Tipo installazione (core, VENV, container, ecc...)_ Core Hassio
 _- Versione package_3.60

Il controllo carichi funziona con le impostazioni salvate precedentemente, ma non è più possibile selezionare il sensore di consumo totale, il sensore dei carichi e gli switch dei carichi, propone solo dei sensori preimpostati e nulla nella selezione degli switch
**Screenshots**
![sensore carichi NON MIEI](https://github.com/user-attachments/assets/a4d05494-dce6-4e00-9957-d6d188218adb)
![switch vuoto](https://github.com/user-attachments/assets/156d26cb-30ef-432b-8c1b-9f8a5fc165ff)

**Comment by Symon84** [comment]
Ciao, io ho installato la versione 2024.12.4 e non riscontro il problema menzionato.. ma mi era successa una cosa simile tempo fa..
Prova a riavviare completamente il sistema e cancellare la cache del browser o dell'app companion..
Io avevo risolto così..

**Comment by Max1963** [comment]
Ok grazie ci proverò, il sistema l'avevo già riavviato completamente ma non
avevo pensato alla cache, grazie ti faccio sapere

Il gio 19 dic 2024, 10:44 Simone ***@***.***> ha scritto:

**Comment by andbad** [comment]
Confermo quanto detto sopra, ho appena aggiornato anche io a 2024.12.4 e non ho problemi.
Sembra che non ti funzioni lo script python, controlla quello.

By(t)e

**Comment by Max1963** [comment]
Ho fatto altre prove, reinstallato tutto il package (versione 3.60) ma niente non funziona più, e dire che ha fatto il suo ottimo lavoro da due anni... Non so più che cosa cercare per farlo funzionare di nuovo...

**Comment by Max1963** [comment]
Questi gli errori nel log di HA:
Registratore: homeassistant.components.automation.powercontrol_configurazione_carica
Fonte: helpers/script.py:2032
Integrazione: Automazione ([documentazione](https://www.home-assistant.io/integrations/automation), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
Prima occorrenza: 20:58:15 (2 occorrenze)
Ultimo accesso: 20:58:15

    PowerControl - Configurazione - Carica: Choose at step 2: choice 1: Error executing script. Error for call_service at pos 2: Invalid option: sensor.shellyem_98cdac1f16da_channel_2_power (possible options: Seleziona, sensor.potenza_carichi_selezionato, sensor.potenza_carichi_sospesa, sensor.potenza_carichi_virtuale, sensor.potenza_fotovoltaico, sensor.potenza_massima_immediato, sensor.potenza_massima_ritardato)
    PowerControl - Configurazione - Carica: Error executing script. Error for choose at pos 2: Invalid option: sensor.shellyem_98cdac1f16da_channel_2_power (possible options: Seleziona, sensor.potenza_carichi_selezionato, sensor.potenza_carichi_sospesa, sensor.potenza_carichi_virtuale, sensor.potenza_fotovoltaico, sensor.potenza_massima_immediato, sensor.potenza_massima_ritardato)

**Comment by andbad** [comment]
Controlla che l'opzione "Nuova modalità selezione opzioni sia disabilitata"

By(t)e

**Comment by Max1963** [comment]
Si, è disabilitata, ma nulla, c'è qualcosa che impedisci il corretto funzionamento, ed è ovviamente nella mia configurazione visto che a tutti funziona perfettamente, ma non so più cosa controllare...

**Comment by Max1963** [comment]
Come ultima ratio ho staccato fisicamente il Rasberry dall'alimentazione, si è riavviato ed ora ha ripreso a funzionare! Evidentemente i riavvii del sistema da HA non sono suffcienti per ricaricare tutto... Grazie per l'assistenza ed ancora complimenti all'autore del package, si può chiudere.

**Comment by riccardo4387** [comment]
Buonasera, mi accodo alla discussione, anche io stesso problema, funzionava tutto per bene e poi di punto in bianco nel menu a tendina non da più la possibilità di selezionare i sensori di casa ma fa selezionare solo quelli della prima immagine già allegata.
Avete idea di come risolvere, ho provato a rimuovere tutto e rimettere e nulla, ho provato anche a spegnere fisicamente il green e riavviare il tutto ma nulla.

Un'altra cosa la parte del recorder potete scrivere gentilmente la striga che andrà copiata al file configuration.yaml

Grazie mille ancora
