### ISSUE TITLE
Dove inserire file .lovelace

### ISSUE THREAD

**Issue by pacioc193** [andbad/HA_PowerControl#7]
Ciao,

volevo provare il tuo progetto ma purtroppo non sono riuscito a capire dove installare il file .lovelace...

Potresti aiutarmi?

Grazie

**Comment by andbad** [comment]
Ciao,
il file ".lovelace" non può essere semplicemente inserito in una qualche cartella, ma devi copiarne il contenuto ed incollarlo nella configurazione di Lovelace.
Quindi fai così:
- copi tutto il testo presente nel file (da "  - title: PC" a "              title: Interruttori Carichi", compresi gli spazi)
- apri la pagina della tua installazione di HomeAssistant
- Clicca sui tre punti in alto a destra
- Clicca su "Modifica plancia"
- Clicca di nuovo sui tre punti in alto a destra
- Clicca su "Editor di configurazione testuale"
- Scorri fino in fondo al codice
- Vai a capo
- Incolla il codice precedentemente copiato
- Clicca su "Salva" in alto a destra
- Clicca sulla "X" in alto a sinistra

Dovresti trovare una nuova pagina col simbolo del tachimetro dove dentro troverai tutte le opzioni del package.

By(t)e
