### ISSUE TITLE
No card configured

### ISSUE THREAD

**Issue by casaerreti** [andbad/HA_PowerControl#8]
Ciao,

sto provando ad installare ma copiando il codice nell'editor lovelace come custom ottengo "No card type configured". Sicuramente sbaglio qualcosa di stupido. Puoi indirizzarmi?

grazie!

f

**Comment by casaerreti** [comment]
Ho trovato fra gli issues chiusi!

provavo ad inserire la card!

grazie ancora

**Comment by andbad** [comment]
Stavo per risponderti. Bene così! :-)

By(t)e
