### ISSUE TITLE
Non riesco a selezionare i dispositivi.

### ISSUE THREAD

**Issue by g45p3r** [andbad/HA_PowerControl#9]
Ciao e complimenti per il tuo lavoro, sono un neofita di home assistant, ho installato il tuo progetto seguendo la guida de "i pensieri dell'architetto" su youtube, d'apprima ha funzionato correttamente, poi dopo qualche giorno, mi sono accorto che non mi permetteva più di selezionare i sensori di controllo carico e nemmeno gli interruttori.
Quando provo a cliccare, anzichè visualizzarmi una lista delle entità selezionabili, mi esce la scritta SELEZIONA, che ovviamente non mi fa nemmeno selezionare.
puoi darmi qualche suggerimento? grazie in anticipo, allego screen.
![screen](https://user-images.githubusercontent.com/98851393/152054999-3f9a4ae0-f3a2-4a52-be6a-54ecf2aaebd4.jpg)
n

**Comment by andbad** [comment]
Quasi sicuramente è un problema relativo allo script python.
Ricontrolla di averlo messo nella cartella corretta il file "update_entities.py" e di aver abilitato gli script:
https://www.home-assistant.io/integrations/python_script/

Fammi sapere.

By(t)e

**Comment by g45p3r** [comment]
Grazie innanzitutto per avermi risposto.
Ho provato più volte a cancellare i due files dalle cartelle pithon_scripts e packages, eliminare il codice da lovelace e rifare tutto da capo dopo aver riavviato il raspberry, ma niente. In configuration.yaml ho inserito le due voci alle righe 12 e 14
![16437936419132895918415964347299](https://user-images.githubusercontent.com/98851393/152126391-a22607fb-a1e0-4c0d-a5b0-181ff5b8af09.jpg)

**Comment by andbad** [comment]
In che cartella hai messo la cartella "python_scripts"?

By(t)e

**Comment by g45p3r** [comment]
Dentro "config" così come packages.
Ma la cosa strana è che mi ha funzionato per un po', poi probabilmente ho toccato qualcosa che non avrei dovuto toccare...
Nonostante abbia provato a reinstallarlo non riesco a farlo funzionare, sempre stesso problema.
Ma eventualmente non c'è modo di impostare manualmente le entità?

**Comment by andbad** [comment]
Per impostare manualmente le entità, devi inserirne il nome negli input text:
input_text.carico_XX_potenza: sensore che misura la potenza assorbita
input_text.carico_XX_switch: interruttore che comanda il carico

Dove XX va da 1 a 20. Puoi farlo da Strumenti per sviluppatori ->  Stati.

In ogni caso cercherei di capire cosa è che non funziona. Potresti ad esempio cominciare ad abilitare i log, inserendo nel tuo file configuration la sezione:
```
logger:
  default: error
  logs:
    homeassistant.components.pc: debug
```

By(t)e

**Comment by g45p3r** [comment]
Non so come ma sono riuscito a farlo partire.
Mi sono accorto che nella plancia energia non mi aggiornava il log.
Un messaggio in giallo mi indicava che era stata disabilitata dal recorder.
Sono andato nel configuration. Yaml, da lì ho rimosso quello che c'era
sotto la voce recorder e tutto ha ripreso a funzionare. Grazie infinite per
la pazienza. E scusami se mi sono espresso con termini non corretti.

Il gio 3 feb 2022, 08:35 andbad ***@***.***> ha scritto:

**Comment by andbad** [comment]
Non c'è problema, sono contento che tu sia riuscito a risolvere.

By(t)e
